Repository SE2-Projekt-WelcomeToTheMoon/app, pull requests merged in 2024-04, with the labels that each got.

#9 8 add main menu
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/se2_projekt_app/MainActivity.java
  app/src/main/java/com/example/se2_projekt_app/screens/Highscore.java
  app/src/main/java/com/example/se2_projekt_app/screens/MainMenu.java
  app/src/main/java/com/example/se2_projekt_app/screens/NetworkDebug.java
  app/src/main/java/com/example/se2_projekt_app/screens/Settings.java
  app/src/main/java/com/example/se2_projekt_app/screens/Singleplayer.java
  app/src/main/res/drawable/background.jpg
  app/src/main/res/drawable/menu_button_default.xml
  app/src/main/res/drawable/menu_button_focused.xml
  app/src/main/res/drawable/menu_button_pressed.xml
  app/src/main/res/drawable/menu_button_selector.xml
  app/src/main/res/layout/highscore.xml
  app/src/main/res/layout/main_menu.xml
  app/src/main/res/layout/settings.xml
  app/src/main/res/layout/singleplayer.xml
  app/src/main/res/values-night/styles.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/refs.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: enhancement

#18 11 create generic json class
  .idea/jsonSchemas.xml
  app/src/main/java/com/example/se2_projekt_app/networking/JSON/ActionValues.java
  app/src/main/java/com/example/se2_projekt_app/networking/JSON/GenerateJSONObject.java
Labels: enhancement

#23 21 connection to lobby from client
  app/build.gradle
  app/src/main/java/com/example/se2_projekt_app/MainActivity.java
  app/src/main/java/com/example/se2_projekt_app/networking/ConnectionHandler.java
  app/src/main/java/com/example/se2_projekt_app/networking/JSON/ActionValues.java
  app/src/main/java/com/example/se2_projekt_app/networking/JSON/GenerateJSONObject.java
  app/src/main/java/com/example/se2_projekt_app/networking/WebSocketClient.java
  app/src/main/java/com/example/se2_projekt_app/networking/WebSocketMessageHandler.java
  app/src/main/java/com/example/se2_projekt_app/screens/MainMenu.java
  app/src/main/java/com/example/se2_projekt_app/screens/Multiplayer.java
Labels: enhancement

#22 Created ConnectionHandler.java class to avoid multiple connectToWebSo…
  app/src/main/java/com/example/se2_projekt_app/networking/ConnectionHandler.java
Labels: enhancement

#27 Branch for issues 25 and 26
  app/src/main/java/com/example/se2_projekt_app/networking/ConnectionHandler.java
  app/src/main/java/com/example/se2_projekt_app/networking/JSON/GenerateJSONObject.java
  app/src/main/java/com/example/se2_projekt_app/networking/WebSocketClient.java
  app/src/main/java/com/example/se2_projekt_app/screens/MainMenu.java
  app/src/main/java/com/example/se2_projekt_app/screens/Multiplayer.java
Labels: enhancement

#28 AddUser + Close Websocket
  .idea/inspectionProfiles/Project_Default.xml
  app/src/main/java/com/example/se2_projekt_app/MainActivity.java
  app/src/main/java/com/example/se2_projekt_app/networking/ConnectionHandler.java
  app/src/main/java/com/example/se2_projekt_app/networking/JSON/GenerateJSONObject.java
  app/src/main/java/com/example/se2_projekt_app/networking/ServerResponseListener.java
  app/src/main/java/com/example/se2_projekt_app/networking/WebSocketClient.java
  app/src/main/java/com/example/se2_projekt_app/networking/WebSocketMessageHandler.java
  app/src/main/java/com/example/se2_projekt_app/screens/MainMenu.java
  app/src/main/java/com/example/se2_projekt_app/screens/Multiplayer.java
  app/src/main/java/com/example/se2_projekt_app/screens/User.java
  app/src/main/java/com/example/se2_projekt_app/screens/UserListAdapter.java
Labels: bug, enhancement

#40 Bug fixed
  app/src/main/java/com/example/se2_projekt_app/networking/WebSocketClient.java
Labels: bug

#43 Excluded files from sonarcloud.
  .idea/misc.xml
  app/build.gradle
Labels: enhancement

#45 Rework GenerateJSONObject class and implement tests
  app/build.gradle
  app/src/main/java/com/example/se2_projekt_app/networking/ConnectionHandler.java
  app/src/main/java/com/example/se2_projekt_app/networking/JSON/GenerateJSONObject.java
  app/src/main/java/com/example/se2_projekt_app/networking/services/JSON/ActionValues.java
  app/src/main/java/com/example/se2_projekt_app/networking/services/JSON/GenerateJSONObject.java
  app/src/main/java/com/example/se2_projekt_app/screens/MainMenu.java
  app/src/main/java/com/example/se2_projekt_app/screens/Multiplayer.java
  app/src/test/java/com/example/se2_projekt_app/networking/services/JSON/GenerateJSONObjectServiceTest.java
  gradle/libs.versions.toml
Labels: enhancement

#46 44-enhance-network-part-of-client
  .idea/inspectionProfiles/Project_Default.xml
  README.md
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/se2_projekt_app/MainActivity.java
  app/src/main/java/com/example/se2_projekt_app/networking/ConnectionHandler.java
  app/src/main/java/com/example/se2_projekt_app/networking/ServerResponseListener.java
  app/src/main/java/com/example/se2_projekt_app/networking/WebSocketClient.java
  app/src/main/java/com/example/se2_projekt_app/networking/WebSocketMessageHandler.java
  app/src/main/java/com/example/se2_projekt_app/networking/json/ActionValues.java
  app/src/main/java/com/example/se2_projekt_app/networking/json/JSONService.java
  app/src/main/java/com/example/se2_projekt_app/networking/responsehandler/PostOffice.java
  app/src/main/java/com/example/se2_projekt_app/networking/responsehandler/ResponseReceiver.java
  app/src/main/java/com/example/se2_projekt_app/networking/services/JSON/ActionValues.java
  app/src/main/java/com/example/se2_projekt_app/screens/MainMenu.java
  app/src/main/java/com/example/se2_projekt_app/screens/Multiplayer.java
  app/src/test/java/com/example/se2_projekt_app/networking/json/JSONServiceTest.java
  gradle/libs.versions.toml
Labels: bug, documentation, enhancement

#48 Enhance lobby system
  app/build.gradle
  app/src/main/java/com/example/se2_projekt_app/networking/json/ActionValues.java
  app/src/main/java/com/example/se2_projekt_app/networking/lobby/LobbyManager.java
  app/src/main/java/com/example/se2_projekt_app/networking/responsehandler/PostOffice.java
  app/src/main/java/com/example/se2_projekt_app/screens/Multiplayer.java
  app/src/main/java/com/example/se2_projekt_app/screens/UserListAdapter.java
  app/src/main/res/layout/activity_multiplayer.xml
Labels: enhancement

#50 deleted duplicate method for startGameButton
  app/src/main/java/com/example/se2_projekt_app/screens/Multiplayer.java
Labels: duplicate

#53 49 implement view for setting username
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/se2_projekt_app/networking/responsehandler/PostOffice.java
  app/src/main/java/com/example/se2_projekt_app/screens/MainMenu.java
  app/src/main/java/com/example/se2_projekt_app/screens/Multiplayer.java
  app/src/main/java/com/example/se2_projekt_app/screens/Username.java
  app/src/main/res/layout/activity_set_username.xml
Labels: enhancement

#17 16 more test coverage
  app/build.gradle
  app/src/androidTest/java/com/example/se2_projekt_app/screens/BasicFlowTest.java
  app/src/androidTest/java/com/example/se2_projekt_app/screens/HighscoreTest.java
  app/src/androidTest/java/com/example/se2_projekt_app/screens/MainMenuTest.java
  gradle/libs.versions.toml
Labels: enhancement

#57 disables testCoverageEnabled
  app/build.gradle
Labels: bug

#59 Replace 'dummy' with actual usernames in LobbyView
  app/src/main/java/com/example/se2_projekt_app/screens/Multiplayer.java
Labels: documentation

#61 Enhance error handling for user creation
  app/build.gradle
  app/src/main/java/com/example/se2_projekt_app/networking/WebSocketClient.java
  app/src/main/java/com/example/se2_projekt_app/networking/json/JSONKeys.java
  app/src/main/java/com/example/se2_projekt_app/screens/MainMenu.java
  app/src/main/java/com/example/se2_projekt_app/screens/Multiplayer.java
  app/src/main/java/com/example/se2_projekt_app/screens/Username.java
  app/src/main/res/layout/activity_set_username.xml
Labels: enhancement
