Repository SE2-Projekt-WelcomeToTheMoon/app, pull requests merged in 2024-06, with the labels that each got.

#93 86 as a user i want to continue the game after a short disconnect
  app/src/main/java/com/example/se2_projekt_app/networking/WebSocketClient.java
  app/src/main/java/com/example/se2_projekt_app/networking/json/JSONKeys.java
  app/src/main/java/com/example/se2_projekt_app/networking/responsehandler/PostOffice.java
  app/src/main/java/com/example/se2_projekt_app/networking/responsehandler/ResponseReceiver.java
  app/src/main/java/com/example/se2_projekt_app/screens/MainMenu.java
Labels: enhancement

#95 Winner screen
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/se2_projekt_app/networking/responsehandler/PostOffice.java
  app/src/main/java/com/example/se2_projekt_app/screens/WinnerScreen.java
  app/src/main/res/layout/winner_screen.xml
Labels: enhancement

#97 87 as a user i want to be able to see the current carddraw
  app/src/main/java/com/example/se2_projekt_app/game/CardController.java
  app/src/main/java/com/example/se2_projekt_app/game/GameBoardManager.java
  app/src/main/java/com/example/se2_projekt_app/networking/responsehandler/PostOffice.java
  app/src/main/java/com/example/se2_projekt_app/screens/GameScreen.java
  app/src/main/java/com/example/se2_projekt_app/views/CardDrawView.java
  app/src/main/java/com/example/se2_projekt_app/views/GameBoardView.java
  app/src/main/res/layout/game_screen.xml
  app/src/test/java/com/example/se2_projekt_app/game/CardControllerTest.java
  app/src/test/java/com/example/se2_projekt_app/game/GameBoardManagerTest.java
Labels: enhancement

#96 94 several improvements and fixes
  app/src/main/java/com/example/se2_projekt_app/game/Chamber.java
  app/src/main/java/com/example/se2_projekt_app/game/Field.java
  app/src/main/java/com/example/se2_projekt_app/game/Floor.java
  app/src/main/java/com/example/se2_projekt_app/game/GameBoardManager.java
  app/src/main/java/com/example/se2_projekt_app/game/GameBoardService.java
  app/src/main/java/com/example/se2_projekt_app/views/GameBoardView.java
  app/src/test/java/com/example/se2_projekt_app/game/ChamberTest.java
  app/src/test/java/com/example/se2_projekt_app/game/FieldTest.java
  app/src/test/java/com/example/se2_projekt_app/game/FloorTest.java
  app/src/test/java/com/example/se2_projekt_app/game/GameBoardManagerTest.java
Labels: bug, enhancement

#100 Winner screen
  app/src/main/java/com/example/se2_projekt_app/networking/responsehandler/PostOffice.java
  app/src/main/java/com/example/se2_projekt_app/screens/GameScreen.java
  app/src/main/java/com/example/se2_projekt_app/screens/WinnerScreen.java
  app/src/main/res/layout/game_screen.xml
Labels: enhancement

#103 System error
  app/src/main/java/com/example/se2_projekt_app/game/GameBoard.java
  app/src/main/java/com/example/se2_projekt_app/game/GameBoardManager.java
  app/src/main/java/com/example/se2_projekt_app/networking/responsehandler/PostOffice.java
  app/src/main/java/com/example/se2_projekt_app/screens/GameScreen.java
  app/src/main/res/drawable/system_error_logo.png
  app/src/main/res/layout/game_screen.xml
  app/src/test/java/com/example/se2_projekt_app/game/GameBoardTest.java
Labels: enhancement

#99 98 as a user i want to actually make a move
  .gitignore
  app/src/main/java/com/example/se2_projekt_app/enums/FieldCategory.java
  app/src/main/java/com/example/se2_projekt_app/enums/GameState.java
  app/src/main/java/com/example/se2_projekt_app/game/CardCombination.java
  app/src/main/java/com/example/se2_projekt_app/game/CardController.java
  app/src/main/java/com/example/se2_projekt_app/game/Chamber.java
  app/src/main/java/com/example/se2_projekt_app/game/Floor.java
  app/src/main/java/com/example/se2_projekt_app/game/GameBoardManager.java
  app/src/main/java/com/example/se2_projekt_app/game/GameBoardService.java
  app/src/main/java/com/example/se2_projekt_app/networking/json/FieldUpdateMessage.java
  app/src/main/java/com/example/se2_projekt_app/networking/responsehandler/PostOffice.java
  app/src/main/java/com/example/se2_projekt_app/screens/GameScreen.java
  app/src/main/java/com/example/se2_projekt_app/screens/Multiplayer.java
  app/src/main/java/com/example/se2_projekt_app/views/CardDrawView.java
  app/src/main/java/com/example/se2_projekt_app/views/GameBoardView.java
  app/src/test/java/com/example/se2_projekt_app/enums/FieldCategoryTest.java
  app/src/test/java/com/example/se2_projekt_app/game/CardControllerTest.java
  app/src/test/java/com/example/se2_projekt_app/game/ChamberTest.java
  app/src/test/java/com/example/se2_projekt_app/game/GameBoardManagerTest.java
  app/src/test/java/com/example/se2_projekt_app/game/GameBoardTest.java
Labels: enhancement

#107 106 rework reward structure
  app/src/main/java/com/example/se2_projekt_app/enums/RewardCategory.java
  app/src/main/java/com/example/se2_projekt_app/game/Chamber.java
  app/src/main/java/com/example/se2_projekt_app/game/Floor.java
  app/src/main/java/com/example/se2_projekt_app/game/GameBoardService.java
  app/src/main/java/com/example/se2_projekt_app/game/Reward.java
  app/src/test/java/com/example/se2_projekt_app/game/GameBoardManagerTest.java
  app/src/test/java/com/example/se2_projekt_app/game/RewardTest.java
Labels: enhancement

#109 Fix sonarcloud high issue
  app/src/main/java/com/example/se2_projekt_app/game/GameBoardManager.java
  app/src/main/java/com/example/se2_projekt_app/networking/responsehandler/PostOffice.java
  app/src/main/java/com/example/se2_projekt_app/screens/GameScreen.java
  app/src/main/java/com/example/se2_projekt_app/screens/MainMenu.java
  app/src/main/java/com/example/se2_projekt_app/screens/WinnerScreen.java
  app/src/main/java/com/example/se2_projekt_app/views/CardDrawView.java
  app/src/main/java/com/example/se2_projekt_app/views/GameBoardView.java
Labels: documentation

#112 111 as a user i do not want to host the game logic on my own
  app/build.gradle
  app/src/main/java/com/example/se2_projekt_app/game/GameBoardManager.java
  app/src/main/java/com/example/se2_projekt_app/networking/WebSocketClient.java
  app/src/main/java/com/example/se2_projekt_app/networking/json/JSONService.java
  app/src/main/java/com/example/se2_projekt_app/screens/MainMenu.java
  app/src/main/java/com/example/se2_projekt_app/screens/Multiplayer.java
  app/src/main/java/com/example/se2_projekt_app/screens/Username.java
  app/src/main/java/com/example/se2_projekt_app/screens/WinnerScreen.java
  app/src/test/java/com/example/se2_projekt_app/networking/json/JSONServiceTest.java
Labels: enhancement

#110 83 as a user i want to be able to see the mission cards
  .gitignore
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/se2_projekt_app/enums/MissionType.java
  app/src/main/java/com/example/se2_projekt_app/game/GameBoardManager.java
  app/src/main/java/com/example/se2_projekt_app/screens/GameScreen.java
  app/src/main/res/drawable/a1.png
  app/src/main/res/drawable/a1_back.png
  app/src/main/res/drawable/a2.png
  app/src/main/res/drawable/a2_back.png
  app/src/main/res/drawable/b1.png
  app/src/main/res/drawable/b1_back.png
  app/src/main/res/drawable/b2.png
  app/src/main/res/drawable/b2_back.png
  app/src/main/res/drawable/c1.png
  app/src/main/res/drawable/c1_back.png
  app/src/main/res/drawable/c2.png
  app/src/main/res/drawable/c2_back.png
  app/src/main/res/layout/game_screen.xml
Labels: bug, enhancement

#114 removed winnerScreenBtn
  app/src/main/res/layout/game_screen.xml
Labels: documentation
